### ISSUE TITLE
Unresponsive

### ISSUE THREAD

**Issue by jacobmcilravey** [synzen/Discord.RSS#41] opened 2018-03-08 09:07 UTC
I've followed each step of the install, configured the bot, twice with 2 branches and a fresh install for each. It starts up and successfully logs in, gives a little speech on starting up correctly, but then it just sits there. 

I can see that the bot is logged in on Discord, it even posts it's status just fine. But it's unresponsive to all commands, no matter what I do.

Any pointers? I could be overlooking something, but I can't seem to find anything I've missed in the setup.

**Comment by Macley-Kun** [comment] 2018-03-08 09:12
What commands do you use? You changed the prefix?

**Comment by jacobmcilravey** [comment] 2018-03-08 09:13
I tried without changing the prefix, and using the default. That didn't work, so I changed it to ! and it still isn't working. I'm using !stats for example just to try something basic, to see if it's responsive.

**Comment by synzen** [comment] 2018-03-08 17:17
Double check to make sure that token belongs to the one you're trying to use
Make sure `config.botSettings.enableCommands` is set to true
Try it on another server with the same bot

**Comment by jacobmcilravey** [comment] 2018-03-08 20:30
The token is correct, the bot can login, both the console says its logged in, and it pops up in discord saying it's online with the configuration for the current "game" it's playing. Commands are also enabled, that's something else it also says in the console.

**Comment by jacobmcilravey** [comment] 2018-03-08 20:30
I'll try another server like you said.

**Comment by Macley-Kun** [comment] 2018-03-09 10:31
You can try skysilk. The servers on there are free during beta. And they also got a free tier that's more then sufficient. On their servers i'm not experiencing anything bad with the bot.

**Comment by synzen** [comment] 2018-03-09 12:55
Oh there might have been some confusion - I meant try it on another *Discord* server.

**Comment by jacobmcilravey** [comment] 2018-03-09 13:14
Haha, I know what you meant. My head is always in Discord mode. We've just tried so many different RSS bots on our server. And being a partner and having a decently large server usually kills public bots. So using this bot is something I'd really like to get going. It didn't seem to work on my private *DISCORD* server either.

**Comment by synzen** [comment] 2018-03-09 13:25
Have you tried the public bot?

**Comment by jacobmcilravey** [comment] 2018-03-09 13:29
We did, but we prefer to not use public bots. We had bad experiences with multiple bot owners in the past. One of which specifically targeted partners for some god awful reason.

**Comment by synzen** [comment] 2018-03-09 14:26
and it worked fine on the public version? If so, then the only possible reason I can think of for it to not work is user error (something you potentially missed). You can try other things like seeing if it works on a different environment, but unfortunately this is as far as I can help you with the given information.

If you know how to, you can also debug it yourself by seeing if the bot sees any messages sent from any servers it's in via the file ./events/message.js

**Comment by Macley-Kun** [comment] 2018-03-12 19:24
@jacobmcilravey you can add me on discord. I can try to help ya hosting it in Heroku if your fine with that.

**Comment by synzen** [comment] 2018-03-28 16:36
I recently discovered an issue where the bot did not respond to uncached guild (server) members. This *may* have been the cause of your issue, but I have doubts it since it's unlikely that for a bot with only a few servers, all the members would most likely be cached - but might be a different case for particularly massive servers.  But of course it's worth a try, if you're still interested. The fix is on dev branch.

If you are no longer pursuing this, you can just ignore this comment and I'll just close the issue within after a week.

**Comment by jacobmcilravey** [comment] 2018-03-28 19:28
We've had issues like this in the past with bots because of our high member count just putting them in the dirt, I'll try to dev branch and see what's possible.

**Comment by Macley-Kun** [comment] 2018-04-11 16:11
@jacobmcilravey Hows it going with using the bot? Any updates :-)

**Comment by synzen** [comment] 2018-04-15 13:33
Closing due to no response for 18 days - assuming solved. Feel free to reopen otherwise.

**Closed by synzen** 2018-04-15 13:33 UTC
